version: "3.7"

services:
  reposistory:
    container_name: reposistory
    image: dockerrepository:latest
    build: .
    ports:
      - "4000:4000"
      - "4001:4001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS="http://+"
    networks:
      - data
    extra_hosts:
      - "localhost:host-gateway"